spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/static/app

