server:
  port: 19010

spring:
  cloud:
    gateway:
      locator:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - predicates:
            - Path=/monitor/**
          uri: lb://styx-monitor
        - predicates:
            - Path=/support/file/**
          uri: lb://styx-support
        - predicates:
            - Path=/support/static/file/**
          uri: lb://styx-support

gateway:
  cors-enabled: true
  # APP静态资源地址匹配模式
  app-path-pattern: /static/app/**
  # APP静态资源地址
  app-resource-path: classpath:/static/app/