spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mapper:
  mappers: com.paladin.framework.mybatis.CustomMapper
  enumAsSimpleType: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

