#logging:
#  level:
#    com.styx: debug

server:
  port: 19021

spring:
  application:
    name: styx-monitor
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    name: msms
    url: jdbc:mysql://172.16.16.125:3306/styx_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15
  redis:
    host: 172.16.16.125
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

monitor:
  shiro:
    login-url: /monitor/login
    session-time: 60
  # 默认密码
  default-password: 1