logging:
  level:
    com:
      styx: DEBUG

server:
  port: 19051

spring:
  application:
    name: styx-support
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.16.125:8848
        namespace: styx
        username: nacos
        password: nacos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    name: styx
    url: jdbc:mysql://172.16.16.125:3306/styx_support?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15
  redis:
    host: 172.16.16.125
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


attachment:
  # 附件上传目录
  upload-folder: E:/upload/
  # 附件访问基础地址
  visit-base-url: /static/file/
  # 上传附件最大大小（单位M）
  max-file-size: 10
  # 附件删除后保留时间（单位天）
  delete-expire-day: 10

